/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.dcode.firmafacil;


import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMaterialLighterIJTheme;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Locale;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Antonio
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
//       // setUndecorated(true); // Primero, establecer undecorated (sin bordes ni botones)
//        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
//        JLabel label = new JLabel("¡Esta es una ventana sin botón de cerrar!");
//        add(label);
//
//        setSize(400, 300);
//        setLocationRelativeTo(null);
//        setVisible(true);
        setUndecorated(false);
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);

        // Agregar un WindowListener para interceptar el evento de cierre
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                // Aquí puedes agregar la lógica que desees cuando el usuario intente cerrar la ventana
                // Por ejemplo, mostrar un diálogo de confirmación antes de cerrarla.
                // En este caso, simplemente no haremos nada para evitar que la ventana se cierre.
                confirmarCierreVentana();
            }
        });

        // Agregar componentes

        setSize(400, 300);
        setLocationRelativeTo(null);
        setVisible(true);

        initComponents();
        InitStyles();
        SetDate();
        InitContent();
    }

    private void confirmarCierreVentana() {
        int opcion = JOptionPane.showConfirmDialog(this, "¿Estás seguro de que deseas cerrar la ventana?",
                "Confirmar Cierre", JOptionPane.YES_NO_OPTION);

        if (opcion == JOptionPane.YES_OPTION) {
            // Si el usuario confirma el cierre, se cierra la ventana
            dispose();
        } else {
            ShowJPanel(new Principal());
        }
    }

    private void InitStyles() {
//    lblInicio.putClientProperty("FlatLaf.style", "font: 14 $light.font");
//    lblInicio.setForeground(Color.black);
//        navText.putClientProperty("FlatLaf.style", "font: bold $h3.regular.font");
//        navText.setForeground(Color.white);
//        dateText.putClientProperty("FlatLaf.style", "font: 24 $light.font");
//        dateText.setForeground(Color.white);
        appName2.putClientProperty("FlatLaf.style", "font: bold $h1.regular.font");
        appName2.setForeground(Color.white);
        
                    
        

    }

    private void SetDate() {
        LocalDate now = LocalDate.now();
        Locale spanishLocale = new Locale("es", "ES");
        // dateText.setText(now.format(DateTimeFormatter.ofPattern("'Hoy es' EEEE dd 'de' MMMM 'de' yyyy", spanishLocale)));
    }

    private void InitContent() {
        ShowJPanel(new Principal());
    }

    public static void ShowJPanel(JPanel p) {
        p.setSize(750, 430);
        p.setLocation(0, 0);

        content.removeAll();
        content.add(p, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        content = new javax.swing.JPanel();
        menu = new javax.swing.JPanel();
        appName2 = new javax.swing.JLabel();
        btnListaDocumento = new javax.swing.JButton();
        btnRegistrarDocumento = new javax.swing.JButton();
        btn_Demanda = new javax.swing.JButton();
        appName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1050, 660));

        background.setBackground(new java.awt.Color(255, 255, 255));

        content.setBackground(new java.awt.Color(255, 255, 255));
        content.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, 865, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)
                .addContainerGap())
        );

        menu.setBackground(new java.awt.Color(13, 71, 161));
        menu.setPreferredSize(new java.awt.Dimension(270, 640));

        appName2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        appName2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        appName2.setText("USER");

        btnListaDocumento.setBackground(new java.awt.Color(21, 101, 192));
        btnListaDocumento.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnListaDocumento.setForeground(new java.awt.Color(255, 255, 255));
        btnListaDocumento.setText("Consultar Documentos");
        btnListaDocumento.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 13, 1, 1, new java.awt.Color(0, 0, 0)));
        btnListaDocumento.setBorderPainted(false);
        btnListaDocumento.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnListaDocumento.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnListaDocumento.setIconTextGap(13);
        btnListaDocumento.setInheritsPopupMenu(true);
        btnListaDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaDocumentoActionPerformed(evt);
            }
        });

        btnRegistrarDocumento.setBackground(new java.awt.Color(21, 101, 192));
        btnRegistrarDocumento.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRegistrarDocumento.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarDocumento.setText("Registrar Documento");
        btnRegistrarDocumento.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 13, 1, 1, new java.awt.Color(0, 0, 0)));
        btnRegistrarDocumento.setBorderPainted(false);
        btnRegistrarDocumento.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnRegistrarDocumento.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnRegistrarDocumento.setIconTextGap(13);
        btnRegistrarDocumento.setInheritsPopupMenu(true);
        btnRegistrarDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarDocumentoActionPerformed(evt);
            }
        });

        btn_Demanda.setBackground(new java.awt.Color(21, 101, 192));
        btn_Demanda.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Demanda.setForeground(new java.awt.Color(255, 255, 255));
        btn_Demanda.setText("Documentos Firmados");
        btn_Demanda.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 13, 1, 1, new java.awt.Color(0, 0, 0)));
        btn_Demanda.setBorderPainted(false);
        btn_Demanda.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_Demanda.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_Demanda.setIconTextGap(13);
        btn_Demanda.setInheritsPopupMenu(true);
        btn_Demanda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DemandaActionPerformed(evt);
            }
        });

        appName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        appName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        appName.setText("FirmaFacil [Firma Electronica]");

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnRegistrarDocumento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnListaDocumento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_Demanda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(menuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(appName, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(appName2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(appName2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(appName, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(btnRegistrarDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnListaDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(menuLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(btn_Demanda, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE)
                    .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnListaDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaDocumentoActionPerformed
        ShowJPanel(new FormListaDocumentoFirmado());
    }//GEN-LAST:event_btnListaDocumentoActionPerformed

    private void btnRegistrarDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarDocumentoActionPerformed
        ShowJPanel(new FormDocumento());
    }//GEN-LAST:event_btnRegistrarDocumentoActionPerformed

    private void btn_DemandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DemandaActionPerformed
        //ShowJPanel(new Returns());

        ShowJPanel(new FormListaDocumentoFirmado());


    }//GEN-LAST:event_btn_DemandaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        FlatMaterialLighterIJTheme.setup();
        System.out.println("Holaa Daboard");


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Dashboard().setVisible(true);

        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel appName;
    private javax.swing.JLabel appName2;
    private javax.swing.JPanel background;
    private javax.swing.JButton btnListaDocumento;
    private javax.swing.JButton btnRegistrarDocumento;
    private javax.swing.JButton btn_Demanda;
    private static javax.swing.JPanel content;
    private javax.swing.JPanel menu;
    // End of variables declaration//GEN-END:variables
}
