package com.dcode.firmafacil;

import static com.dcode.firmafacil.Dashboard.ShowJPanel;
import com.dcode.firmafacil.Data.DCategoria;
import com.dcode.firmafacil.Data.DCliente;
import com.dcode.firmafacil.Data.DDocumento;
import com.dcode.firmafacil.Data.DServicio;
import com.dcode.firmafacil.Modelo.Documento;
import com.dcode.firmafacil.Modelo.ServicioDocumento;
import com.google.gson.Gson;
import java.io.IOException;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Base64;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import com.dcode.firmafacil.Data.DDocumentoFirmado;

public class FormListaDocumentoFirmado extends javax.swing.JPanel {

    boolean editar = false;
//    MDemanda demandaEditar;

    public FormListaDocumentoFirmado() {
        initComponents();
        InitStyles();
        CargarCLiente();
        // Mostrar1;
        // CargarCuentaBancoCMB();
    }

    private void CargarCLiente() {
        DCliente dCliente = new DCliente();
        List<String> clientes = dCliente.ListClienteString();

        for (String nom : clientes) {
            cmbCliente2.addItem(nom);
        }
    }

    public void ListarDocumentosFirmados() {

        String selecCliente = (String) cmbCliente2.getSelectedItem();
        int codigoCliente = obtenerCodigoClientePorNombre(selecCliente);

        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("IdDocumento");
          modelo.addColumn("NombreDocumento");
        modelo.addColumn("Empresa");
        modelo.addColumn("Categoria");
        modelo.addColumn("Ruta");
        modelo.addColumn("FechaFirma");
        modelo.addColumn("FechaVigencia");
         modelo.addColumn("NombreUsuario");

        jTableServicioDocumento.setModel(modelo);

        DDocumentoFirmado documentoFirmado = new DDocumentoFirmado();
        List<ServicioDocumento> serviciodocumentoList = documentoFirmado.SelectDocumentoByCliente(codigoCliente);
        System.out.println(" Traer datos " + serviciodocumentoList);

        String servicioDocForTable[] = new String[8];
        for (ServicioDocumento item : serviciodocumentoList) {

            servicioDocForTable[0] = "" + item.getIdDocumento();
            servicioDocForTable[1] = "" + item.getNombreDocumento();
            servicioDocForTable[2] = item.getEmpresa();
            servicioDocForTable[3] = item.getCategoria();
            servicioDocForTable[4] = "" + item.getArchivoOrigen();
            servicioDocForTable[5] = "" + item.getFechaServicio();
            servicioDocForTable[6] = "" + item.getFechaVigencia();
            servicioDocForTable[7] = item.getUsuarioFirma();
            modelo.addRow(servicioDocForTable);
        }

        jTableServicioDocumento.setModel(modelo);
    }

    private void InitStyles() {

//        if (demandaEditar != null) {
//
//            //Mostrar(cuentaEditar);
//            System.out.println("InitStyles >>> " + demandaEditar);
//
//         //   txtFactura.setText(demandaEditar.getDocumento());
//           // txtDeudaPendiente.setEnabled(false);
//
//       //     String doc = cuentaEditar.getDocumento();
//         //   CuentaDetalle cuentaDet = new CuentaDetalle();
//           // cuentaDet.setDocumento(doc);
//            //MostrarListaCuentaDetalle(cuentaDet);
//
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableServicioDocumento = new javax.swing.JTable();
        header1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnRegistrarDocumento = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cmbCliente2 = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));

        bg.setBackground(new java.awt.Color(255, 255, 255));

        jTableServicioDocumento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableServicioDocumento.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(jTableServicioDocumento);

        header1.setBackground(new java.awt.Color(25, 118, 210));
        header1.setPreferredSize(new java.awt.Dimension(744, 150));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Listado de Documentos [Firma Electronica]");

        javax.swing.GroupLayout header1Layout = new javax.swing.GroupLayout(header1);
        header1.setLayout(header1Layout);
        header1Layout.setHorizontalGroup(
            header1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(header1Layout.createSequentialGroup()
                .addGap(260, 260, 260)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(253, Short.MAX_VALUE))
        );
        header1Layout.setVerticalGroup(
            header1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(header1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        btnRegistrarDocumento.setBackground(new java.awt.Color(18, 90, 173));
        btnRegistrarDocumento.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRegistrarDocumento.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarDocumento.setText("Buscar");
        btnRegistrarDocumento.setToolTipText("");
        btnRegistrarDocumento.setBorderPainted(false);
        btnRegistrarDocumento.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnRegistrarDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarDocumentoActionPerformed(evt);
            }
        });

        jLabel1.setText("Cliente");

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(header1, javax.swing.GroupLayout.DEFAULT_SIZE, 816, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
            .addGroup(bgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbCliente2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegistrarDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(bgLayout.createSequentialGroup()
                .addComponent(header1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(btnRegistrarDocumento, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                                .addGap(19, 19, 19))
                            .addGroup(bgLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(cmbCliente2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private int obtenerCodigoClientePorNombre(String selecCliente) {
       DDocumentoFirmado dCliente = new DDocumentoFirmado();
    return dCliente.obtenerCodigoClientePorNombre(selecCliente); 
    
    }

    private static class ApiResponse {

        String estado;
        String data;
    }

    public class Informacion {

        private String data;
        private String nombre;

        public Informacion(String data, String nombre) {
            this.data = data;
            this.nombre = nombre;
        }

        public Informacion() {
        }

        public String getData() {
            return data;
        }

        public void setData(String data) {
            this.data = data;
        }

        public String getNombre() {
            return nombre;
        }

        public void setNombre(String nombre) {
            this.nombre = nombre;
        }

    }


    private void btnRegistrarDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarDocumentoActionPerformed
        // TODO add your handling code here:
        ListarDocumentosFirmados();
        
    }//GEN-LAST:event_btnRegistrarDocumentoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton btnRegistrarDocumento;
    private javax.swing.JComboBox<String> cmbCliente2;
    private javax.swing.JPanel header1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableServicioDocumento;
    // End of variables declaration//GEN-END:variables
}
