package com.dcode.firmafacil;

import static com.dcode.firmafacil.Dashboard.ShowJPanel;
import com.dcode.firmafacil.Data.DDocumento;
import com.dcode.firmafacil.Data.DServicio;
import com.dcode.firmafacil.Modelo.Documento;
import com.dcode.firmafacil.Modelo.ServicioDocumento;
import com.google.gson.Gson;
import java.io.IOException;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Base64;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

public class FormListaDocumento extends javax.swing.JPanel {

    boolean editar = false;
//    MDemanda demandaEditar;

    public FormListaDocumento() {
        initComponents();
        InitStyles();
        Mostrar(1);
        // CargarCuentaBancoCMB();
    }
    //Sobreescritura

//    public PlantillaCrud(MDemanda mDemandaEdit) {
//        System.out.println("Inicializando Cuenta CRUD" + mDemandaEdit);
//        initComponents();
//        editar = true;
//        this.demandaEditar = mDemandaEdit;
//        InitStyles();
//      //  Mostrar(mDemandaEdit);
//
//    }
//    public void CargarCuentaBancoCMB() {
//        cmbCuentaBanco.removeAllItems();
//        UtilitariosJDBC utilJdbc = new UtilitariosJDBC();
//        List<Poldat> cuentasList = utilJdbc.SelectCuentasBancosCmb();
//        System.out.println("Cargar Combo: " + cuentasList);
////
////        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>(cuentasList.toArray(new String[0]));
////        cmbCuentaBanco.setModel(model);
//
//        for (Poldat poldat : cuentasList) {
//            System.out.println("Llenando Combo: " + poldat.rtstr1);
//            cmbCuentaBanco.addItem(poldat.rtstr1);
//        }
//    }
    public void Mostrar(int IdCliente) {

        System.out.println("Mostrar Listado Documentos!!! ");

        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("IdDocumento");
        modelo.addColumn("Empresa");
        modelo.addColumn("Categoria");
        modelo.addColumn("ArchivoOrigen");
        modelo.addColumn("Firmado");
        modelo.addColumn("FechaServicio");
        modelo.addColumn("FechaVigencia");
        modelo.addColumn("NombreUsuario");

        jTableServicioDocumento.setModel(modelo);

        DServicio servicio = new DServicio();
        List<ServicioDocumento> serviciodocumentoList = servicio.SelectDocumentoByCliente(1);
        System.out.println(" Traer datos " + serviciodocumentoList);

        String servicioDocForTable[] = new String[8];
        for (ServicioDocumento item : serviciodocumentoList) {

            servicioDocForTable[0] = "" + item.getIdDocumento();
            servicioDocForTable[1] = item.getEmpresa();
            servicioDocForTable[2] = item.getCategoria();
            servicioDocForTable[3] = "*.pdf";
            servicioDocForTable[4] = "" + item.getIdServicio();
            servicioDocForTable[5] = "" + item.getFechaServicio();
            servicioDocForTable[6] = "" + item.getFechaVigencia();
            servicioDocForTable[6] = item.getUsuarioFirma();
            modelo.addRow(servicioDocForTable);
        }

        jTableServicioDocumento.setModel(modelo);
    }

    private void InitStyles() {

//        if (demandaEditar != null) {
//
//            //Mostrar(cuentaEditar);
//            System.out.println("InitStyles >>> " + demandaEditar);
//
//         //   txtFactura.setText(demandaEditar.getDocumento());
//           // txtDeudaPendiente.setEnabled(false);
//
//       //     String doc = cuentaEditar.getDocumento();
//         //   CuentaDetalle cuentaDet = new CuentaDetalle();
//           // cuentaDet.setDocumento(doc);
//            //MostrarListaCuentaDetalle(cuentaDet);
//
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        txtFactura = new javax.swing.JTextField();
        btnFirmarDocumento = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableServicioDocumento = new javax.swing.JTable();
        header1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnRegistrarDocumento = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        bg.setBackground(new java.awt.Color(255, 255, 255));

        btnFirmarDocumento.setBackground(new java.awt.Color(0, 153, 102));
        btnFirmarDocumento.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnFirmarDocumento.setForeground(new java.awt.Color(255, 255, 255));
        btnFirmarDocumento.setText("Firmar Documento");
        btnFirmarDocumento.setBorderPainted(false);
        btnFirmarDocumento.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnFirmarDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirmarDocumentoActionPerformed(evt);
            }
        });

        jTableServicioDocumento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableServicioDocumento.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(jTableServicioDocumento);

        header1.setBackground(new java.awt.Color(25, 118, 210));
        header1.setPreferredSize(new java.awt.Dimension(744, 150));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Listado de Documentos [Firma Electronica]");

        javax.swing.GroupLayout header1Layout = new javax.swing.GroupLayout(header1);
        header1.setLayout(header1Layout);
        header1Layout.setHorizontalGroup(
            header1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(header1Layout.createSequentialGroup()
                .addGap(260, 260, 260)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        header1Layout.setVerticalGroup(
            header1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(header1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        btnRegistrarDocumento.setBackground(new java.awt.Color(18, 90, 173));
        btnRegistrarDocumento.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRegistrarDocumento.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarDocumento.setText("Registrar");
        btnRegistrarDocumento.setBorderPainted(false);
        btnRegistrarDocumento.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnRegistrarDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarDocumentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(header1, javax.swing.GroupLayout.DEFAULT_SIZE, 816, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addComponent(btnRegistrarDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84)
                        .addComponent(btnFirmarDocumento)))
                .addContainerGap())
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(bgLayout.createSequentialGroup()
                .addComponent(header1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFactura, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(btnFirmarDocumento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRegistrarDocumento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    private void btnFirmarDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirmarDocumentoActionPerformed
        // TODO add your handling code here:

        if (jTableServicioDocumento.getSelectedRow() > -1) {
            
            Documento docObj= new Documento();
            DDocumento d= new DDocumento();
            
             String idDocumento = (String) jTableServicioDocumento
                    .getValueAt(jTableServicioDocumento.getSelectedRow(), 0);
             System.out.println("idDocumento Firmas: " + idDocumento);
             
             
             docObj.setIdDocumento(Integer.parseInt(idDocumento));

            ShowJPanel(new FormFirmaDocumento(d.SelectByIdDocumentoObject(docObj)));
        }

  
    }//GEN-LAST:event_btnFirmarDocumentoActionPerformed

    

    private void btnRegistrarDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarDocumentoActionPerformed
        // TODO add your handling code here:
        ShowJPanel(new FormDocumento());
    }//GEN-LAST:event_btnRegistrarDocumentoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton btnFirmarDocumento;
    private javax.swing.JButton btnRegistrarDocumento;
    private javax.swing.JPanel header1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableServicioDocumento;
    private javax.swing.JTextField txtFactura;
    // End of variables declaration//GEN-END:variables
}
